import { Vazirmatn, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from './components/context/CartContext';
import Header from './components/Header';

const vazir = Vazirmatn({
  variable: '--font-vazir',
  subsets: ['arabic'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: 'فروشگاه کتاب',
    template: '%s | فروشگاه کتاب'
  },
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazir.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <Header />
          <main>
            {children}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
